--liquibase formatted sql

--changeset akimov-ve:countries_insert

insert into countries (ru, ua, be, en, es, pt, de, fr, it, pl, js, lt, lv, cz)
values
('Азербайджан', 'Азербайджан', 'Азэрбайджан', 'Azerbaijan', 'Azerbaiyán', 'Azerbaijão', 'Aserbaidschan', 'Azerbaïdjan', 'Azerbaijan', 'Azerbejdżan', 'アゼルバイジャン', 'Azerbaidžanas', 'Azerbaidžāna', 'Ázerbajdžán'),
('Алжир', 'Алжир', 'Альжыр', 'Algeria', 'Argelia', 'Argélia', 'Algerien', 'Algérie', 'Algeria', 'Algeria', 'アルジェリア', 'Alžyras', 'Alžīrija', 'Alžírsko'),
('Ангола', 'Ангола', 'Ангола', 'Angola', 'Angola', 'Angola', 'Angola', 'Angola', 'Angola', 'Angola', 'アンゴラ', 'Angola', 'Angola', 'Angola'),
('Великобритания', 'Великобританiя', 'Вялікабрытанія', 'United Kingdom', 'Gran Bretaña', 'Reino Unido', 'Großbritannien', 'Grande-Bretagne', 'Regno Unito', 'Wielka Brytania', 'イギリス', 'Didžioji Britanija', 'Apvienotā Karaliste', 'Velká Británie'),
('Россия', 'Росiя', 'Расея', 'Russia', 'Rusia', 'Rússia', 'Russland', 'Russie', 'Russia', 'Rosja', 'ロシア', 'Rusija', 'Krievija', 'Rusko'),
('США', 'США', 'ЗША', 'USA', 'EE.UU.', 'EUA', 'USA', 'USA', 'Stati Uniti', 'USA', 'アメリカ合衆国', 'JAV', 'ASV', 'USA'),
('Ирак', 'Iрак', 'Ірак', 'Iraq', 'Irak', 'Iraque', 'Irak', 'Irak', 'Iraq', 'Irak', 'イラク', 'Irakas', 'Irāka', 'Irák'),
('Грузия', 'Грузiя', 'Грузія', 'Georgia', 'Georgia', 'Geórgia', 'Georgien', 'Géorgie', 'Georgia', 'Gruzja', 'グルジア', 'Gruzija', 'Gruzija', 'Gruzie'),
('Мексика', 'Мексика', 'Мэксыка', 'Mexico', 'México', 'México', 'Mexiko', 'Mexique', 'Messico', 'Meksyk', 'メキシコ', 'Meksika', 'Meksika', 'Mexiko'),
('Белиз', 'Белiз', 'Бэліз', 'Belize', 'Belice', 'Belize', 'Belize', 'Bélize', 'Belize', 'Belize', 'ベリーズ', 'Belizas', 'Belīza', 'Belize'),
('Аруба', 'Аруба', 'Аруба', 'Aruba', 'Aruba', 'Aruba', 'Aruba', 'Aruba', 'Aruba', 'Aruba', 'アルバ', 'Aruba', 'Aruba', 'Aruba'),
('Бутан', 'Бутан', 'Бутан', 'Bhutan', 'Bután', 'Butão', 'Bhutan', 'Bouthan', 'Bhutan', 'Bhutan', 'ブータン', 'Butanas', 'Butāna', 'Bhútán'),
('Дания', 'Данiя', 'Данія', 'Denmark', 'Dinamarca', 'Dinamarca', 'Dänemark', 'Danemark', 'Danimarca', 'Dania', 'デンマーク', 'Danija', 'Dānija', 'Dánsko'),
('Монголия', 'Монголiя', 'Манголія', 'Mongolia', 'Mongolia', 'Mongólia', 'Mongolei', 'Mongolie', 'Mongolia', 'Mongolia', 'モンゴル', 'Mongolija', 'Mongolija', 'Mongolsko'),
('Монако', 'Монако', 'Манака', 'Monaco', 'Mónaco', 'Mónaco', 'Monaco', 'Monaco', 'Monaco', 'Monako', 'モナコ', 'Monakas', 'Monako', 'Monako'),
('Гаити', 'Гаїтi', 'Гаіці', 'Haiti', 'Haití', 'Haiti', 'Haiti', 'Haïti', 'Haiti', 'Haiti', 'ハイチ', 'Haitis', 'Haiti', 'Haiti'),
('Ирландия', 'Iрландiя', 'Ірляндыя', 'Ireland', 'Irlanda', 'Irlanda', 'Irland', 'Irlande', 'Irlanda', 'Irlandia', 'アイルランド', 'Airija', 'Īrija', 'Irsko'),
('Мали', 'Малi', 'Малі', 'Mali', 'Mali', 'Mali', 'Mali', 'Mali', 'Mali', 'Mali', 'マリ', 'Malis', 'Mali', 'Mali'),
('Конго', 'Конго', 'Конга', 'Congo', 'Congo', 'Congo', 'Kongo', 'Congo', 'Congo', 'Kongo', 'コンゴ', 'Kongas', 'Kongo', 'Kongo (Brazzaville)'),
('Гуам', 'Гуам', 'Гуам', 'Guam', 'Guam', 'Guam', 'Guam', 'Guam', 'Guam', 'Guam', 'グアム', 'Guamas', 'Guama', 'Guam'),
('Куба', 'Куба', 'Куба', 'Cuba', 'Cuba', 'Cuba', 'Kuba', 'Cuba', 'Cuba', 'Kuba', 'キューバ', 'Kuba', 'Kuba', 'Kuba'),
('Лаос', 'Лаос', 'Ляос', 'Laos', 'Laos', 'Laos', 'Laos', 'Laos', 'Laos', 'Laos', 'ラオス', 'Laosas', 'Laosa', 'Laos'),
('Ливия', 'Лiвiя', 'Лібія', 'Libya', 'Libia', 'Líbia', 'Libyen', 'Lybie', 'Libia', 'Libia', 'リビア', 'Libija ', 'Lībija', 'Lybie'),
('Гана', 'Гана', 'Гана', 'Ghana', 'Ghana', 'Gana', 'Ghana', 'Ghana', 'Ghana', 'Ghana', 'ガーナ', 'Gana', 'Gana', 'Ghana'),
('Гамбия', 'Гамбiя', 'Гамбія', 'Gambia', 'Gambia', 'Gâmbia', 'Gambia', 'Gambie', 'Gambia', 'Gambia', 'ガンビア', 'Gambija', 'Gambija', 'Gambie'),
('Бельгия', 'Бельгiя', 'Бэльгія', 'Belgium', 'Bélgica', 'Bélgica', 'Belgien', 'Belgique', 'Belgio', 'Belgia', 'ベルギー', 'Belgija', 'Beļģija', 'Belgie'),
('Бенин', 'Бенiн', 'Бэнін', 'Benin', 'Benín', 'Benin', 'Benin', 'Bénin', 'Benin', 'Benin', 'ベナン', 'Beninas', 'Benīna', 'Benin'),
('Джибути', 'Джiбутi', 'Джыбуці', 'Djibouti', 'Yibuti', 'Djibouti', 'Djibouti', 'Djibouti', 'Djibouti', 'Dżibuti', 'ジブチ', 'Džibutis', 'Džibuti', 'Džibutsko'),
('Кипр', 'Кiпр', 'Кіпар', 'Cyprus', 'Chipre', 'Chipre', 'Zypern', 'Chypre', 'Cipro', 'Cypr', 'キプロス', 'Kipras', 'Kipra', 'Kypr'),
('Молдова', 'Молдова', 'Малдова', 'Moldova', 'Moldavia', 'Moldávia', 'Moldavien', 'Moldavie', 'Moldavia', 'Mołdawia', 'モルドバ', 'Moldova', 'Moldova', 'Moldavsko'),
('Латвия', 'Латвiя', 'Латвія', 'Latvia', 'Letonia', 'Letónia', 'Lettland', 'Lettonie', 'Lettonia', 'Łotwa', 'ラトヴィア', 'Latvija', 'Latvija', 'Lotyšsko'),
('Италия', 'Iталiя', 'Італія', 'Italy', 'Italia', 'Itália', 'Italien', 'Italie', 'Italia', 'Włochy', 'イタリア', 'Italija', 'Itālija', 'Itálie'),
('Китай', 'Китай', 'Кітай', 'China', 'China', 'China', 'China', 'Chine', 'Cina', 'Chiny', '中国', 'Kinija', 'Ķīna', 'Čína'),
('Замбия', 'Замбiя', 'Замбія', 'Zambia', 'Zambia', 'Zâmbia', 'Sambia', 'Zambie', 'Egitto', 'Zambia', 'ザンビア', 'Zambija', 'Zambija', 'Zambie'),
('Гвинея', 'Гвiнея', 'Гвінэя', 'Guinea', 'Guinea', 'Guiné', 'Guinea', 'Guinée', 'Guinea', 'Gwinea', 'ギニア', 'Gvinėja', 'Gvineja', 'Guinea'),
('Макао', 'Макао', 'Макаа', 'Macau', 'Macao', 'Macau', 'Macao', 'Macao', 'Macao', 'Makao', 'マカオ', 'Macao', 'Makao', 'Macao'),
('Индия', 'Iндiя', 'Індыя', 'India', 'India', 'Índia', 'Indien', 'Inde', 'India', 'Indie', 'インド', 'Indija', 'Indija', 'Indie'),
('Кения', 'Кенiя', 'Кенія', 'Kenya', 'Kenia', 'Quénia', 'Kenia', 'Kenya', 'Kenia', 'Kenia', 'ケニア', 'Kenija', 'Kēnija', 'Keňa'),
('Малави', 'Малавi', 'Малаві', 'Malawi', 'Malawi', 'Malawi', 'Malawi', 'Malawi', 'Malawi', 'Malawi', 'マラウィ', 'Malavis<br>', 'Malavi', 'Malawi'),
('Гайана', 'Гайана', 'Гаяна', 'Guyana', 'Guyana', 'Guiana', 'Guyana', 'Guyana', 'Guyana', 'Gujana', 'ガイアナ', 'Gajana', 'Gajana', 'Guyana'),
('Йемен', 'Йемен', 'Емэн', 'Yemen', 'Yemen', 'Iémen', 'Jemen', 'Yémen', 'Yemen', 'Jemen', 'イエメン', 'Jemenas', 'Jemena', 'Jemen'),
('Катар', 'Катар', 'Катар', 'Qatar', 'Qatar', 'Qatar', 'Katar', 'Qatar', 'Qatar', 'Katar', 'カタール', 'Kataras', 'Katāra', 'Katar'),
('Малайзия', 'Малайзiя', 'Малайзія', 'Malaysia', 'Malasia', 'Malásia', 'Malaysia', 'Malaisie', 'Malesia', 'Malezja', 'マレーシア', 'Malaizija', 'Malaizija', 'Malajsie'),
('Коморы', 'Комори', 'Каморы', 'Comoros', 'Comoras', 'Comores', 'Komoren', 'Comores', 'Comoros', 'Komory', 'コモロ諸島', 'Komorai', 'Komoru salas', 'Komory'),
('Маврикий', 'Маврикiй', 'Маўрыцы', 'Mauritius', 'Mauricio', 'Maurícia', 'Mauritius', 'Maurice', 'Mauritius', 'Mauritius', 'モーリシャス', 'Mauricijus', 'Mavrikija', 'Mauricius'),
('Мьянма', 'М''янма', 'М''янма', 'Myanmar', 'Birmania', 'Mianmar', 'Myanmar', 'Birmanie', 'Myanmar', 'Birma', 'ミャンマー', 'Birma', 'Mjanma', 'Myanmar'),
('Германия', 'Нiмеччина', 'Нямеччына', 'Germany', 'Alemania', 'Alemanha', 'Deutschland', 'Allemagne', 'Germania', 'Niemcy', 'ドイツ', 'Vokietija', 'Vācija', 'Německo'),
('Науру', 'Науру', 'Навуру', 'Nauru', 'Nauru', 'Nauru', 'Nauru', 'Nauru', 'Nauru', 'Nauru', 'ナウル', 'Nauru', 'Nauru', 'Nauru'),
('Непал', 'Непал', 'Нэпал', 'Nepal', 'Nepal', 'Nepal', 'Nepal', 'Népal', 'Nepal', 'Nepal', 'ネパール', 'Nepalas', 'Nepāla', 'Nepál'),
('Ватикан', 'Ватикан', 'Ватыкан', 'Vatican', 'Vaticano', 'Vaticano', 'Vatikan', 'Vatican', 'Vaticano', 'Watykan', 'ヴァチカン', 'Vatikanas', 'Vatican', 'Vatikán'),
('Уганда', 'Уганда', 'Уганда', 'Uganda', 'Uganda', 'Uganda', 'Uganda', 'Ouganda', 'Uganda', 'Uganda', 'ウガンダ', 'Uganda', 'Uganda', 'Uganda'),
('Эстония', 'Естонiя', 'Эстонія', 'Estonia', 'Estonia', 'Estónia', 'Estland', 'Estonie', 'Estonia', 'Estonia', 'エストニア', 'Estija', 'Igaunija', 'Estonsko'),
('Сингапур', 'Сiнгапур', 'Сынґапур', 'Singapore', 'Singapur', 'Singapura', 'Singapur', 'Singapour', 'Singapore', 'Singapur', 'シンガポール', 'Singapūras', 'Singapūra', 'Singapur'),
('Ямайка', 'Ямайка', 'Ямайка', 'Jamaica', 'Jamaica', 'Jamaica', 'Jamaika', 'Jamaïque', 'Giamaica', 'Jamajka', 'ジャマイカ', 'Jamaika', 'Jamaika', 'Jamajka'),
('Нигер', 'Нiгер', 'Нігер', 'Niger', 'Níger', 'Níger', 'Niger', 'Niger', 'Niger', 'Niger', 'ニジェール', 'Nigeris', 'Nigera', 'Niger'),
('Никарагуа', 'Нiкарагуа', 'Нікарагуа', 'Nicaragua', 'Nicaragua', 'Nicarágua', 'Nicaragua', 'Nicaragua', 'Nicaragua', 'Nikaragua', 'ニカラグア', 'Nikaragva', 'Nikaragva', 'Nikaragua'),
('Эфиопия', 'Ефiопiя', 'Этыёпія', 'Ethiopia', 'Etiopía', 'Etiópia', 'Äthiopien', 'Ethiopie', 'Etiopia', 'Etiopia', 'エチオピア', 'Etiopija', 'Etiopija', 'Etiopie'),
('Сербия', 'Сербiя', 'Сэрбія', 'Serbia', 'Serbia', 'Sérvia', 'Serbien', 'Serbie', 'Serbia', 'Serbia', 'セルビア', 'Serbija', 'Serbija', 'Srbsko'),
('Габон', 'Габон', 'Габон', 'Gabon', 'Gabón', 'Gabão', 'Gabon', 'Gabon', 'Gabon', 'Gabon', 'ガボン', 'Gabonas', 'Gabona', 'Gabon'),
('Турция', 'Туреччина', 'Турэччына', 'Turkey', 'Turquía', 'Turquia', 'Türkei', 'Turquie', 'Turchia', 'Turcja', 'トルコ', 'Turkija', 'Turcija', 'Turecko'),
('Судан', 'Судан', 'Судан', 'Sudan', 'Sudán', 'Sudão', 'Sudan', 'Soudan', 'Sudan', 'Sudan', 'スーダン', 'Sudanas', 'Sudāna', 'Súdán'),
('Багамы', 'Багами', 'Багамы', 'Bahamas', 'Bahamas', 'Bahamas', 'Bahamas', 'Bahamas', 'Bahamas', 'Bahama', 'バハマ', 'Bahamai', 'Bahamu salas', 'Bahamy'),
('Ниуэ', 'Нiуе', 'Нівуэ', 'Niue', 'Niue', 'Niue', 'Niue', 'Niue', 'Niue', 'Niue', 'ニウエ', 'Niue<br>', 'Niue', 'Niue'),
('Того', 'Того', 'Тога', 'Togo', 'Togo', 'Togo', 'Togo', 'Togo', 'Togo', 'Togo', 'トーゴ', 'Togas', 'Togo', 'Togo'),
('Хорватия', 'Хорватiя', 'Харватыя', 'Croatia', 'Croacia', 'Croácia', 'Kroatien', 'Croatie', 'Croazia', 'Chorwacja', 'クロアチア', 'Kroatija', 'Horvātija', 'Chorvatsko'),
('Бахрейн', 'Бахрейн', 'Бахрэйн', 'Bahrain', 'Bahréin', 'Bahrein', 'Bahrain', 'Bahreïn', 'Bahrain', 'Bahrain', 'バーレーン', 'Bahreinas', 'Bahreina', 'Bahrajn'),
('Таиланд', 'Таїланд', 'Тайлянд', 'Thailand', 'Tailandia', 'Tailândia', 'Thailand', 'Thaïlande', 'Tailandia', 'Tajlandia', 'タイ', 'Tailandas', 'Tailanda', 'Thajsko'),
('Сомали', 'Сомалi', 'Самалі', 'Somalia', 'Somalia', 'Somália', 'Somalia', 'Somalie', 'Somalia', 'Somalia', 'ソマリア', 'Somalis', 'Somali', 'Somálsko'),
('Палау', 'Палау', 'Палаў', 'Palau', 'Palaos', 'Palau', 'Palau', 'Palaos', 'Palau', 'Palau', 'パラウ', 'Palau', 'Palava', 'Palau'),
('Токелау', 'Токелау', 'Такелаў', 'Tokelau', 'Tokelau', 'Tokelau', 'Tokelau', 'Tokelau', 'Tokelau', 'Tokelau', 'トケラウ', 'Tokelau', 'Tokelava', 'Tokelau'),
('Франция', 'Францiя', 'Францыя', 'France', 'Francia', 'França', 'Frankreich', 'France', 'Francia', 'Francja', 'フランス', 'Prancūzija', 'Francija', 'Francie'),
('Финляндия', 'Фiнляндiя', 'Фінляндыя', 'Finland', 'Finlandia', 'Finlândia', 'Finnland', 'Finlande', 'Finlandia', 'Finlandia', 'フィンランド', 'Suomija', 'Somija', 'Finsko'),
('Израиль', 'Iзраїль', 'Ізраіль', 'Israel', 'Israel', 'Israel', 'Israel', 'Israël', 'Israele', 'Izrael', 'イスラエル', 'Izraelis', 'Izraela', 'Izrael'),
('Шри-Ланка', 'Шрi-Ланка', 'Шры-Лянка', 'Sri Lanka', 'Sri-Lanka', 'Sri Lanka', 'Sri Lanka', 'Sri Lanka', 'Sri Lanka', 'Sri Lanka', 'スリランカ', 'Šri Lanka', 'Šrilanka', 'Srí Lanka'),
('Самоа', 'Самоа', 'Самоа', 'Samoa', 'Samoa', 'Samoa', 'Samoa', 'Samoa', 'Samoa', 'Samoa', 'サモア', 'Samoa', 'Samoa', 'Samoa'),
('Сенегал', 'Сенегал', 'Сэнэгал', 'Senegal', 'Senegal', 'Senegal', 'Senegal', 'Sénégal', 'Senegal', 'Senegal', 'セネガル', 'Senegalas<br>', 'Senegāla', 'Senegal'),
('Свазиленд', 'Свазiленд', 'Свазылэнд', 'Swaziland', 'Suazilandia', 'Suazilândia', 'Swasiland', 'Swaziland', 'Swaziland', 'Swaziland', 'スワジランド', 'Svazilendas', 'Svazilenda', 'Svazijsko'),
('Бермуды', 'Бермуди', 'Бэрмуды', 'Bermuda', 'Bermudas', 'Bermudas', 'Bermudas', 'Bermudes', 'Bermuda', 'Bermudy', 'バミューダ', 'Bermudai', 'Bermudu salas', 'Bermudské ostrovy'),
('Словения', 'Словенiя', 'Славенія', 'Slovenia', 'Eslovenia', 'Eslovénia', 'Slowenien', 'Slovénie', 'Slovenia', 'Słowenia', 'スロベニア', 'Slovėnija', 'Slovēnija', 'Slovinsko'),
('Тайвань', 'Тайвань', 'Тайвань', 'Taiwan', 'Taiwan', 'Taiwan', 'Taiwan', 'Taïwan', 'Taiwan', 'Tajwan', '台湾', 'Taivanas', 'Taivāna', 'Tchaj-wan'),
('Чили', 'Чилi', 'Чылі', 'Chile', 'Chile', 'Chile', 'Chile', 'Chili', 'Cile', 'Chile', 'チリ', 'Čilė', 'Čīle', 'Chile'),
('Фиджи', 'Фiджi', 'Фіджы', 'Fiji', 'Fiyi', 'Fiji', 'Fidschi', 'Fidji', 'Fiji', 'Fidżi', 'フィジー', 'Fidžis', 'Fidži', 'Fidži'),
('Тувалу', 'Тувалу', 'Тувалу', 'Tuvalu', 'Tuvalu', 'Tuvalu', 'Tuvalu', 'Tuvalu', 'Tuvalu', 'Tuvalu', 'ツバル', 'Tuvalu', 'Tuvalu', 'Tuvalu'),
('Норвегия', 'Норвегiя', 'Нарвэгія', 'Norway', 'Noruega', 'Noruega', 'Norwegen', 'Norvège', 'Norvegia', 'Norwegia', 'ノルウェー', 'Norvegija', 'Norvēģija', 'Norsko'),
('Руанда', 'Руанда', 'Руанда', 'Rwanda', 'Ruanda', 'Ruanda', 'Ruanda', 'Rwanda', 'Ruanda', 'Rwanda', 'ルアンダ', 'Ruanda', 'Ruanda', 'Rwanda'),
('Чад', 'Чад', 'Чад', 'Chad', 'Chad', 'Chade', 'Tschad', 'Tchad', 'Chad', 'Czad', 'チャド', 'Čadas', 'Čada', 'Čad'),
('Остров Мэн', 'Острiв Мен', 'Выспа Мэн', 'Isle of Man', 'Islas Man', 'Ilha de Man', 'Insel Man', 'Ile de Man', 'Isola di Man', 'Isle of Man', 'マン島', 'Meno sala', 'Mēna', 'Ostrov Man'),
('Оман', 'Оман', 'Аман', 'Oman', 'Omán', 'Omã', 'Oman', 'Oman', 'Oman', 'Oman', 'オマーン', 'Omanas', 'Omāna', 'Omán'),
('Панама', 'Панама', 'Панама', 'Panama', 'Panamá', 'Panamá', 'Panama', 'Panama', 'Panama', 'Panama', 'パナマ', 'Panama', 'Panama', 'Panama'),
('Перу', 'Перу', 'Пэру', 'Peru', 'Perú', 'Peru', 'Peru', 'Pérou', 'Peru', 'Peru', 'ペルー', 'Peru', 'Peru', 'Peru'),
('Реюньон', 'Реюньон', 'Рэюньён', 'Réunion', 'Reunión', 'Réunion', 'Réunion', 'Réunion', 'Réunion', 'Réunion', 'レユニオン', 'Reunionas', 'Reinjona', 'Réunion'),
('Эквадор', 'Еквадор', 'Эквадор', 'Ecuador', 'Ecuador', 'Equador', 'Ecuador', 'Equateur', 'Ecuador', 'Ekwador', 'エクアドル', 'Ekvadoras', 'Ekvadora', 'Ekvádor'),
('Кыргызстан', 'Киргизстан', 'Кыргызтан', 'Kyrgyzstan', 'Kirguistán', 'Quirguistão', 'Kirgisistan', 'Kirghizstan', 'Kyrgyzstan', 'Kirgistan', 'キルギスタン', 'Kirgizija', 'Kirgizstāna', 'Kyrgyzstán'),
('Иран', 'Iран', 'Іран', 'Iran', 'Irán', 'Irão', 'Iran', 'Iran', 'Iran', 'Iran', 'イラン', 'Iranas', 'Irāna', 'Írán'),
('Сейшелы', 'Сейшели', 'Сэйшэлы', 'Seychelles', 'Seychelles', 'Seicheles', 'Seychellen', 'Seychelles', 'Seychelles', 'Seszele', 'セイシェル', 'Seišeliai', 'Seišelu salas', 'Seychely'),
('Марокко', 'Марокко', 'Марока', 'Morocco', 'Marruecos', 'Marrocos', 'Marokko', 'Maroc', 'Marocco', 'Maroko', 'モロッコ', 'Marokas', 'Maroka', 'Maroko'),
('Кабо-Верде', 'Кабо-Верде', 'Каба-Вэрдэ', 'Cape Verde', 'Cabo Verde', 'Cabo Verde', 'Kap Verde', 'Cap Vert', 'Cabo Verde', 'Cape Verde', 'カーボベルデ', 'Žaliasis Kyšulys', 'Kaboverde', 'Kapverdy'),
('Доминика', 'Домiнiка', 'Дамініка', 'Dominica', 'Dominica', 'Dominica', 'Dominica', 'Dominique', 'Dominica', 'Dominika', 'ドミニカ', 'Dominika', 'Dominika', 'Dominika'),
('Острова Кайман', 'Острови Кайман', 'Выспы Кайман', 'Cayman Islands', 'Islas Caimán', 'Ilhas Caimão', 'Kaimaninseln', 'Iles Caïman', 'Isole Cayman', 'Kajmany', 'ケイマン諸島', 'Kaimanų salos', 'Kaimana salas', 'Kajmanské ostrovy'),
('Зимбабве', 'Зiмбабве', 'Зімбабвэ', 'Zimbabwe', 'Zimbabue', 'Zimbabwe', 'Simbabwe', 'Zimbabwe', 'Zimbabwe', 'Zimbabwe', 'ジンバブエ', 'Zimbabvė', 'Zimbabve', 'Zimbabwe'),
('Саудовская Аравия', 'Саудiвська Аравiя', 'Саудаўская Арабія', 'Saudi Arabia', 'Arabia Saudí', 'Arábia Saudita', 'Saudi Arabien', 'Arabie Saoudite', 'Arabia Saudita', 'Arabia Saudyjska', 'サウジアラビア', 'Saudo Arabija', 'Sauda Arābija', 'Saúdská Arábie'),
('Гренада', 'Гренада', 'Грэнада', 'Grenada', 'Granada', 'Granada', 'Grenada', 'Grenade', 'Grenada', 'Grenada', 'グレナダ', 'Grenada', 'Granāda', 'Grenada'),
('Монтсеррат', 'Монтсеррат', 'Мантсэрат', 'Montserrat', 'Montserrat', 'Montserrat', 'Montserrat', 'Montserrat', 'Montserrat', 'Montserrat', 'モントセラト', 'Monseratas', 'Montserrata', 'Montserrat'),
('Мальта', 'Мальта', 'Мальта', 'Malta', 'Malta', 'Malta', 'Malta', 'Malte', 'Malta', 'Malta', 'マルタ', 'Malta', 'Malta', 'Malta'),
('Таджикистан', 'Таджикистан', 'Таджыкістан', 'Tajikistan', 'Tadjikistán', 'Tadjiquistão', 'Tadschikistan', 'Tadjikistan', 'Tajikistan', 'Tadżykistan', 'タジキスタン', 'Tadžikistanas', 'Tadžikistāna', 'Tádžikistán'),
('Уругвай', 'Уругвай', 'Уруґвай', 'Uruguay', 'Uruguay', 'Uruguai', 'Uruguay', 'Uruguay', 'Uruguay', 'Urugwaj', 'ウルグアイ', 'Urugvajus', 'Urugvaja', 'Uruguay'),
('Казахстан', 'Казахстан', 'Казахстан', 'Kazakhstan', 'Kazajistán', 'Cazaquistão', 'Kasachstan', 'Kazakhstan', 'Kazakistan', 'Kazachstan', 'カザフスタン', 'Kazachstanas', 'Kazahstāna', 'Kazachstán'),
('Тунис', 'Тунiс', 'Туніс', 'Tunisia', 'Túnez', 'Tunísia', 'Tunesien', 'Tunisie', 'Tunisia', 'Tunezja', 'チュニス', 'Tunisas', 'Tunisija', 'Tunisko'),
('Канада', 'Канада', 'Канада', 'Canada', 'Canadá', 'Canadá', 'Kanada', 'Canada', 'Canada', 'Kanada', 'カナダ', 'Kanada', 'Kanāda', 'Kanada'),
('Восточный Тимор', 'Схiдний Тимор', 'Усходні Тымор', 'East Timor', 'Timor Oriental', 'Timor-Leste', 'Ost Timor', 'Timor oriental', 'Timor Est', 'Wschodni Timor', '東ティモール', 'Rytų Timoras', 'Austrumu Timora', 'Východní Timor'),
('Ангилья', 'Ангілья', 'Анґілья', 'Anguilla', 'Anguilla', 'Anguilla', 'Anguilla', 'Anguilla', 'Anguilla', 'Anguilla', 'アンギラ', 'Angilija', 'Angilja', 'Anguilla'),
('Тонга', 'Тонга', 'Тонга', 'Tonga', 'Tonga', 'Tonga', 'Tonga', 'Tonga', 'Tonga', 'Tonga', 'トンガ', 'Tongas', 'Tonga', 'Tonga'),
('Индонезия', 'Iндонезiя', 'Інданэзія', 'Indonesia', 'Indonesia', 'Indonésia', 'Indonesien', 'Indonésie', 'Indonesia', 'Indonezja', 'インドネシア', 'Indonezija', 'Indonēzija', 'Indonésie'),
('Синт-Мартен', 'Сінт-Мартен', 'Сінт-Мартэн', 'Sint Maarten', 'Sint Maarten', 'São Martinho (Caraíbas)', 'Sint Maarten', 'Saint-Martin', 'Sint Maarten', 'Saint Martin', 'シント・マールテン', 'Sint Martenas ', 'Sint Maarten', 'Sint Maarten'),
('Мозамбик', 'Мозамбiк', 'Мазамбік', 'Mozambique', 'Mozambique', 'Moçambique', 'Mosambik', 'Mozambique', 'Mozambico', 'Mozambik', 'モザンビーク', 'Mozambikas', 'Mozambika', 'Mosambik'),
('Болгария', 'Болгарiя', 'Баўгарыя', 'Bulgaria', 'Bulgaria', 'Bulgária', 'Bulgarien', 'Bulgarie', 'Bulgaria', 'Bułgaria', 'ブルガリア', 'Bulgarija', 'Bulgārija', 'Bulharsko'),
('Иордания', 'Йорданiя', 'Іярданія', 'Jordan', 'Jordania', 'Jordânia', 'Jordanien', 'Jordanie', 'Giordania', 'Jordania', 'ヨルダン', 'Jordanija', 'Jordānija', 'Jordánsko'),
('Греция', 'Грецiя', 'Грэцыя', 'Greece', 'Grecia', 'Grécia', 'Griechenland', 'Grèce', 'Grecia', 'Grecja', 'ギリシャ', 'Graikija', 'Grieķija', 'Řecko'),
('Либерия', 'Лiберiя', 'Лібэрыя', 'Liberia', 'Liberia', 'Libéria', 'Liberia', 'Libéria', 'Liberia', 'Liberia', 'リベリア', 'Liberija', 'Libērija', 'Libérie'),
('Словакия', 'Словаччина', 'Славаччына', 'Slovakia', 'Eslovaquia', 'Eslováquia', 'Slowakei', 'Slovaquie', 'Slovacchia', 'Słowacja', 'スロヴァキア', 'Slovakija', 'Slovākija', 'Slovensko'),
('Коста-Рика', 'Коста-Рiка', 'Коста-Рыка', 'Costa Rica', 'Costa Rica', 'Costa Rica', 'Costa Rica', 'Costa Rica', 'Costa Rica', 'Costa Rica', 'コスタリカ', 'Kosta Rika', 'Kostarika', 'Kostarika'),
('Румыния', 'Румунiя', 'Румынія', 'Romania', 'Rumanía', 'Roménia', 'Rumänien', 'Roumanie', 'Romania', 'Rumunia', 'ルーマニア', 'Rumunija', 'Rumānija', 'Rumunsko'),
('Намибия', 'Намiбiя', 'Намібія', 'Namibia', 'Namibia', 'Namíbia', 'Namibia', 'Namibie', 'Namibia', 'Namibia', 'ナミビア', 'Namibija', 'Namībija', 'Namibie'),
('Лесото', 'Лесото', 'Лесота', 'Lesotho', 'Lesoto', 'Lesoto', 'Lesotho', 'Leshoto', 'Lesotho', 'Lesotho', 'レソト', 'Lesotas', 'Lesoto', 'Lesotho'),
('Македония', 'Македонiя', 'Македонія', 'Macedonia', 'Macedonia', 'Macedónia', 'Mazedonien', 'Macédoine', 'Macedonia', 'Macedonia', 'マケドニア', 'Makedonija', 'Makedonija', 'Makedonie'),
('Гонконг', 'Гонконг', 'Ганконг', 'Hong Kong', 'Hong Kong', 'Hong Kong', 'Hong Kong', 'Hong Kong', 'Hong Kong', 'Hong Kong', '香港', 'Honkongas', 'Gonkonga', 'Hongkong'),
('Ливан', 'Лiван', 'Лібан', 'Lebanon', 'Líbano', 'Líbano', 'Libanon', 'Liban', 'Libano', 'Liban', 'レバノン', 'Libanas', 'Livāna', 'Libanon'),
('Нигерия', 'Нiгерiя', 'Нігерыя', 'Nigeria', 'Nigeria', 'Nigéria', 'Nigeria', 'Nigéria', 'Nigeria', 'Nigeria', 'ナイジェリア', 'Nigerija', 'Nigērija', 'Nigérie'),
('Танзания', 'Танзанiя', 'Танзанія', 'Tanzania', 'Tanzania', 'Tanzânia', 'Tansania', 'Tanzanie', 'Tanzania', 'Tanzania', 'タンザニア', 'Tanzanija', 'Tanzānija', 'Tanzanie'),
('Тринидад и Тобаго', 'Тринiдад i Тобаго', 'Трынідад і Табага', 'Trinidad and Tobago', 'Trinidad y Tobago', 'Trinidad e Tobago', 'Trinidad und Tobago', 'Trinité et Tobago', 'Trinidad e Tobago', 'Trinidad and Tobago', 'トリニダード・トバゴ', 'Trinidadas ir Tobagas', 'Trindada un Tobago', 'Trinidad a Tobago'),
('Гватемала', 'Гватемала', 'Гватэмала', 'Guatemala', 'Guatemala', 'Guatemala', 'Guatemala', 'Guatemala', 'Guatemala', 'Guatemala', 'グアテマラ', 'Gvatemala', 'Gvatemala', 'Guatemala'),
('Пакистан', 'Пакистан', 'Пакістан', 'Pakistan', 'Pakistán', 'Paquistão', 'Pakistan', 'Pakistan', 'Pakistan', 'Pakistan', 'パキスタン', 'Pakistanas', 'Pakistāna', 'Pákistán'),
('Кот д`Ивуар', 'Кот-д''iвуар', 'Кот д`Івуар', 'Côte d`Ivoire', 'Costa de Marfil', 'Costa do Marfim', 'Elfenbeinküste', 'Côte d''Ivoire', 'Costa d''Avorio', 'Wybrzeże Kości Słoniowej', 'コートジボアール', 'Dramblio Kaulo Krantas', 'Kotdivuāra', 'Pobřeží slonoviny'),
('Япония', 'Японiя', 'Японія', 'Japan', 'Japón', 'Japão', 'Japan', 'Japon', 'Giappone', 'Japonia', '日本', 'Japonija', 'Japāna', 'Japonsko'),
('Гибралтар', 'Гiбралтар', 'Гібралтар', 'Gibraltar', 'Gibraltar', 'Gibraltar', 'Gibraltar', 'Gibraltar', 'Gibilterra', 'Gibraltar', 'ジブラルタル', 'Gibraltaras', 'Gibraltāra', 'Gibraltar'),
('Западная Сахара', 'Захiдна Сахара', 'Заходняя Сахара', 'Western Sahara', 'Sáhara Occidental', 'Saara Ocidental', 'Westsahara', 'Sahara occidental', 'Sahara Occidentale', 'Sahara Zachodnia', '西サハラ', 'Vakarų Sachara', 'Rietumsahāra', 'Západní Sahara'),
('Мартиника', 'Мартинiка', 'Мартыніка', 'Martinique', 'Martinica', 'Martinica', 'Martinique', 'Martinique', 'Martinique', 'Martynika', 'マルティニク', 'Martinika', 'Martinika', 'Martinik'),
('Узбекистан', 'Узбекистан', 'Узбэкістан', 'Uzbekistan', 'Uzbekistán', 'Uzbequistão', 'Usbekistan', 'Ouzbékistan', 'Uzbekistan', 'Uzbekistan', 'ウズベキスタン', 'Uzbekistanas', 'Uzbekistāna', 'Uzbekistán'),
('Венгрия', 'Угорщина', 'Вугоршчына', 'Hungary', 'Hungría', 'Hungria', 'Ungarn', 'Hongrie', 'Ungheria', 'Węgry', 'ハンガリー', 'Vengrija', 'Ungārija', 'Maďarsko'),
('Люксембург', 'Люксембург', 'Люксэмбург', 'Luxembourg', 'Luxemburgo', 'Luxemburgo', 'Luxemburg', 'Luxembourg', 'Lussemburgo', 'Luxembourg', 'ルクセンブルク', 'Liuksemburgas', 'Luksemburga', 'Lucembursko'),
('Филиппины', 'Фiлiппiни', 'Філіпіны', 'Philippines', 'Filipinas', 'Filipinas', 'Philippinen', 'Philippines', 'Filippine', 'Filipiny', 'フィリピン', 'Filipinai', 'Filipīnas', 'Filipíny'),
('Бразилия', 'Бразилiя', 'Бразылія', 'Brazil', 'Brasil', 'Brasil', 'Brasilien', 'Brésil', 'Brasile', 'Brazylia', 'ブラジル', 'Brazilija', 'Brazīlija', 'Brazílie'),
('Испания', 'Iспанiя', 'Гішпанія', 'Spain', 'España', 'Espanha', 'Spanien', 'Espagne', 'Spagna', 'Hiszpania', 'スペイン', 'Ispanija', 'Spānija', 'Španělsko'),
('Уоллис и Футуна', 'Уоллiс i Футуна', 'Ўоліс і Футуна', 'Wallis and Futuna', 'Wallis y Futuna', 'Wallis e Futuna', 'Wallis und Futuna', 'Wallis et Futuna', 'Wallis e Futuna', 'Wallis i Futuna', 'ウォリス・フツナ', 'Vallisas ir Futuna', 'Volisa un Futuna', 'Wallis a Futuna'),
('Австрия', 'Австрiя', 'Аўстрыя', 'Austria', 'Austria', 'Áustria', 'Österreich', 'Autriche', 'Austria', 'Austria', 'オーストリア', 'Austrija', 'Austrija', 'Rakousko'),
('Мавритания', 'Мавританiя', 'Маўрытанія', 'Mauritania', 'Mauritania', 'Mauritânia', 'Mauretanien', 'Mauritanie', 'Mauritania', 'Mauretania', 'モーリタニア', 'Mauritanija', 'Mavritānija', 'Mauritánie'),
('Афганистан', 'Афганiстан', 'Аўганістан', 'Afghanistan', 'Afganistán', 'Afeganistão', 'Afghanistan', 'Afghanistan', 'Afghanistan', 'Afganistan', 'アフガニスタン', 'Afganistanas', 'Afganistāna', 'Afghánistán'),
('Литва', 'Литва', 'Летува', 'Lithuania', 'Lituania', 'Lituânia', 'Litauen', 'Lituanie', 'Lituania', 'Litwa', 'リトアニア', 'Lietuva', 'Lietuva', 'Litva'),
('Беларусь', 'Бiлорусь', 'Беларусь', 'Belarus', 'Bielorrusia', 'Bielorrússia', 'Weißrussland', 'Belorus', 'Bielorussia', 'Białoruś', 'ベラルーシ', 'Baltarusija', 'Baltkrievija', 'Bělorusko'),
('Швейцария', 'Швейцарiя', 'Швайцарыя', 'Switzerland', 'Suiza', 'Suíça', 'Schweiz', 'Suisse', 'Svizzera', 'Szwajcaria', 'スイス', 'Šveicarija', 'Šveice', 'Švýcarsko'),
('Новая Каледония', 'Нова Каледонiя', 'Новая Каледонія', 'New Caledonia', 'Nueva Caledonia', 'Nova Caledónia', 'Neukaledonien', 'Nouvelle Calédonie', 'Nuova Caledonia', 'Nowa Kaledonia', 'ニューカレドニア', 'Naujoji Kaledonija', 'Jaunkaledonija', 'Nová Kaledonie'),
('Кюрасао', 'Кюрасао', 'Кюрасаа', 'Curaçao', 'Antillas Holandesas', 'Curaçao', 'Niederländische Antillen', 'Antilles Néerlandaises', 'Antille Olandesi', 'Curacao', 'キュラソー島', 'Kiurasao ', 'Nīderlandes Antilas', 'Curaçao'),
('Фарерские острова', 'Фарерськi острови', 'Фарэрскія выспы', 'Faroe Islands', 'Islas Feroe', 'Ilhas Feroe', 'Färöer', 'Iles Féroé', 'Isole Faroe', 'Wyspy Owcze', 'フェロー諸島', 'Farerų salos', 'Fāru salas', 'Faerské ostrovy'),
('Туркменистан', 'Туркменістан', 'Туркмэністан', 'Turkmenistan', 'Turkmenistán', 'Turquemenistão', 'Turkmenistan', 'Turkménistan', 'Turkmenistan', 'Turkmenistan', 'トルクメニスタン', 'Turkmėnistanas', 'Turkmenistāna', 'Turkmenistán'),
('Боливия', 'Болiвiя', 'Балівія', 'Bolivia', 'Bolivia', 'Bolívia', 'Bolivien', 'Bolivie', 'Bolivia', 'Boliwia', 'ボリビア', 'Bolivija', 'Bolīvija', 'Bolívie'),
('Папуа - Новая Гвинея', 'Папуа - Нова Гвiнея', 'Папуа - Новая Ґвінэя', 'Papua New Guinea', 'Papúa Nueva Guinea', 'Papua-Nova Guiné', 'Papua-Neuguinea', 'Papouasie-Nouvelle Guinée', 'Papua Nuova Guinea', 'Papua Nowa Gwinea', 'パプア・ニューギニア', 'Papua - Naujoji Gvinėja', 'Papua Jaungvineja', 'Papua Nová Guinea'),
('Соломоновы Острова', 'Соломоновi Острови', 'Саламонавы выспы', 'Solomon Islands', 'Islas Salomón', 'Ilhas Salomão', 'Salomoninseln', 'Iles Salomon', 'Isole Solomon', 'Wyspy Solomona', 'ソロモン諸島', 'Saliamono salos', 'Zālamanu salas', 'Šalomounovy ostrovy'),
('Мадагаскар', 'Мадагаскар', 'Мадагаскар', 'Madagascar', 'Madagascar', 'Madagáscar', 'Madagaskar', 'Madagascar', 'Madagascar', 'Madagaskar', 'マダガスカル', 'Madagaskaras', 'Madagaskāra', 'Madagaskar'),
('Экваториальная Гвинея', 'Екваторiальна Гвiнея', 'Экватарыяльная Гвінэя', 'Equatorial Guinea', 'Guinea Ecuatorial', 'Guiné Equatorial', 'Äquatorialguinea', 'Guinée équatoriale', 'Guinea Equatoriale', 'Gwinea Równikowa', '赤道ギニア', 'Pusiaujo Gvinėja', 'Ekvotoriāla Gvineja', 'Rovníková Guinea'),
('Камерун', 'Камерун', 'Камэрун', 'Cameroon', 'Camerún', 'Camarões', 'Kamerun', 'Cameroun', 'Camerun', 'Kamerun', 'カメルーン', 'Kamerūnas', 'Kameruna', 'Kamerun'),
('Бруней-Даруссалам', 'Бруней-Дарусалам', 'Брунэй-Дарусалам', 'Brunei Darussalam', 'Brunéi', 'Brunei Darussalam', 'Brunei Darussalam', 'Bruneï', 'Brunei Darussalam', 'Brunei', 'ブルネイ・ダルサラーム', 'Brunėjaus Dar Es Salamas', 'Bruneja', 'Brunej'),
('Украина', 'Україна', 'Украіна', 'Ukraine', 'Ucrania', 'Ucrânia', 'Ukraine', 'Ukraine', 'Ucraina', 'Ukraina', 'ウクライナ', 'Ukraina', 'Ukraina', 'Ukrajina'),
('Черногория', 'Чорногорiя', 'Чарнагорыя', 'Montenegro', 'Montenegro', 'Montenegro', 'Montenegro', 'Monténégro', 'Montenegro', 'Czarnogóra', 'モンテネグロ', 'Juodkalnija', 'Melnkalne', 'Černá Hora'),
('Сьерра-Леоне', 'Сьєрра-Леоне', 'Сьера-Леонэ', 'Sierra Leone', 'Sierra Leona', 'Serra Leoa', 'Sierra Leone', 'Sierra Leone', 'Sierra Leone', 'Sierra Leone', 'シエラレオネ', 'Siera Leonė', 'Sjero-Leone', 'Sierra Leone'),
('Сальвадор', 'Сальвадор', 'Сальвадор', 'El Salvador', 'El Salvador', 'Salvador', 'El Salvador', 'Salvador', 'El Salvador', 'Salwador', 'サルバドール', 'Salvadoras', 'Salvadora', 'Salvador'),
('Новая Зеландия', 'Нова Зеландiя', 'Новая Зэляндыя', 'New Zealand', 'Nueva Zelanda', 'Nova Zelândia', 'Neuseeland', 'Nouvelle Zélande', 'Nuova Zelanda', 'Nowa Zelandia', 'ニュージーランド', 'Naujoji Zelandija', 'Jaunzelande', 'Nový Zéland'),
('Сирийская Арабская Республика', 'Сiрiйська Арабська Республiка', 'Сырыйская Арабская Рэспубліка', 'Syria', 'Siria', 'República Árabe da Síria', 'Syrien', 'Syrie', 'Siria', 'Syria', 'シリア・アラブ共和国', 'Sirija', 'Sīrija', 'Sýrie'),
('Французская Гвиана', 'Французька Гвiана', 'Француская Гвіяна', 'French Guiana', 'Guayana Francesa', 'Guiana Francesa', 'Französisch-Guayana', 'Guyane française', 'Guiana Francese', 'Gujana Francuska', 'フランス領ガイアナ', 'Prancūzijos Gviana', 'Franču Gviāna', 'Francouzská Guyana'),
('Австралия', 'Австралiя', 'Аўстралія', 'Australia', 'Australia', 'Austrália', 'Australien', 'Australie', 'Australia', 'Australia', 'オーストラリア', 'Australija', 'Austrālija', 'Austrálie'),
('Андорра', 'Андорра', 'Андора', 'Andorra', 'Andorra', 'Andorra', 'Andorra', 'Andorre', 'Andorra', 'Andorra', 'アンドラ', 'Andora', 'Andora', 'Andorra'),
('Венесуэла', 'Венесуела', 'Вэнэсуэла', 'Venezuela', 'Venezuela', 'Venezuela', 'Venezuela', 'Vénézuela', 'Venezuela', 'Wenezuela', 'ベネズエラ', 'Venesuela', 'Venesuela', 'Venezuela'),
('Объединенные Арабские Эмираты', 'Об''єднанi Арабськi Емiрати', 'Аб''яднаныя Арабскія Эміраты', 'United Arab Emirates', 'Emiratos Árabes Unidos', 'Emirados Árabes Unidos', 'Vereinigte Arabische Emirate', 'Emirats Arabes Unis', 'Emirati Arabi Uniti', 'Zjednoczone Emiraty Arabskie', 'アラブ首長国連邦', 'Jungtiniai Arabų Emyratai', 'Apvienotie Arābu Emirati', 'Spojené arabské emiráty'),
('Сан-Марино', 'Сан-Марiно', 'Сан-Марына', 'San Marino', 'San Marino', 'San Marino', 'San Marino', 'Saint-Marin', 'San Marino', 'San Marino', 'サンマリノ', 'San Marinas', 'Sanmarino', 'San Marino'),
('Гвинея-Бисау', 'Гвiнея-Бiсау', 'Гвінэя-Бісава', 'Guinea-Bissau', 'Guinea-Bissau', 'Guiné-Bissau', 'Guinea-Bissau', 'Guinée Bissau', 'Guinea-Bissau', 'Gwinea-Bissau', 'ギニア・ビサウ', 'Gvinėja Bisau', 'Gvineja-Bisava', 'Guinea-Bissau'),
('Бангладеш', 'Бангладеш', 'Бангладэш', 'Bangladesh', 'Bangladesh', 'Bangladesh', 'Bangladesch', 'Bengladesh', 'Bangladesh', 'Bangladesz', 'バングラディシュ', 'Bangladešas', 'Bangladeša', 'Bangladéš'),
('Ботсвана', 'Ботсвана', 'Батсвана', 'Botswana', 'Botswana', 'Botswana', 'Botswana', 'Botswana', 'Botswana', 'Botswana', 'ボツワナ', 'Botsvana', 'Botstvana', 'Botswana'),
('Албания', 'Албанiя', 'Альбанія', 'Albania', 'Albania', 'Albânia', 'Albanien', 'Albanie', 'Albania', 'Albania', 'アルバニア', 'Albanija', 'Albānija', 'Albánie'),
('Гренландия', 'Гренландiя', 'Грэнляндыя', 'Greenland', 'Groenlandia', 'Gronelândia<br>', 'Grönland', 'Groenland', 'Groenlandia', 'Grenlandia', 'グリーンランド', 'Grenlandija', 'Grenlande', 'Grónsko'),
('Южный Судан', 'Південний Судан', 'Паўднёвы Судан', 'South Sudan', 'Sudán del Sur', 'Sudão do Sul', 'Republik Südsudan', 'République du Soudan du Sud', 'Repubblica del Sudan del Sud', 'Sudan Południowy', '南スーダン', 'Pietų Sudanas ', 'South Sudan', 'Jižní Súdán'),
('Северная Корея', 'Пiвнiчна Корея', 'Паўночная Карэя', 'North Korea', 'Corea del Norte', 'Coreia do Norte', 'Nordkorea', 'Corée du Nord', 'Corea del Nord', 'Korea Północna', '北朝鮮', 'Šiaurės Korėja', 'Ziemeļkoreja', 'Severní Korea'),
('Остров Норфолк', 'Острiв Норфолк', 'Выспа Норфалк', 'Norfolk Island', 'Islas Norfolk', 'Ilha Norfolk', 'Norfolkinsel', 'Ile Norfolk', 'Isola di Norfolk', 'Wyspa Norfolk', 'ノーフォーク諸島', 'Norfolko sala', 'Norfolka', 'Ostrov Norfolk'),
('Виргинские острова, США', 'Вiргiнськi острови, США', 'Віргінскія выспы, ЗША', 'US Virgin Islands', 'Islas Virginia (EE.UU.)', 'Ilhas Virgens Americanas', 'US Jungferninseln', 'Iles Vierges Américaines', 'Isole Virgin degli Stati Uniti', 'Amerykańskie Wyspy Dziewicze', 'アメリカ領ヴァージン諸島', 'Mergelių salos, JAV', 'Virdžīnijas salas, ASV', 'Americké Panenské ostrovy'),
('Гондурас', 'Гондурас', 'Гандурас', 'Honduras', 'Honduras', 'Gordura', 'Honduras', 'Honduras', 'Honduras', 'Honduras', 'ホンジュラス', 'Hondūras', 'Gondurasa', 'Honduras'),
('Доминиканская Республика', 'Домiнiканська Республiка', 'Дамініканская Рэспубліка', 'Dominican Republic', 'República Dominicana', 'República Dominicana', 'Dominikanische Republik', 'République dominicaine', 'Repubblica Domenicana', 'Dominikana', 'ドミニカ共和国', 'Dominikos Respublika', 'Dominikānas Republika', 'Dominikánská republika'),
('Гваделупа', 'Гваделупа', 'Ґўадэлюпа', 'Guadeloupe', 'Guadalupe (Francia)', 'Guadalupe', 'Guadeloupe', 'Guadeloupe', 'Guadeloupe', 'Guadeloupa', 'グアドループ', 'Gvadelupa', 'Gvadelupa', 'Guadeloupe'),
('Кувейт', 'Кувейт', 'Кувэйт', 'Kuwait', 'Kuwait', 'Kuwait<br>', 'Kuwait', 'Koweït', 'Kuwait', 'Kuwejt', 'クウェート', 'Kuveitas', 'Kuveita', 'Kuvajt'),
('Центрально-Африканская Республика', 'Центральноафриканська Республiка', 'Цэнтральна-Афрыканская Рэспубліка', 'Central African Republic', 'República Centroafricana', 'República Centro-Africana', 'Zentralafrikanische Republik', 'République centrafricaine', 'Repubblica Centro Africana', 'Republika Środkowo-Afrykańska', '中央アフリカ共和国', 'Centrinės Afrikos Respublika', 'Centrālāfrikas Republika', 'Středoafrická republika'),
('Северные Марианские острова', 'Пiвнiчнi Марiанськi острови', 'Паўночныя Марыянскія выспы', 'Northern Mariana Islands', 'Islas Marianas del Norte', 'Ilhas Marianas', 'Nördliche Marianen', 'Iles Mariannes du Nord', 'Isole Northern Mariana', 'Wyspy Północnej Mariany', '北マリアナ諸島', 'Šiaurės Marianų salos', 'Ziemeļu Marianas Salas', 'Mariánské ostrovy'),
('Чехия', 'Чехiя', 'Чэхія', 'Czech Republic', 'Chequia', 'República Checa', 'Tschechische Republik', 'République tchèque', 'Repubblica Ceca', 'Czechy', 'チェコ', 'Čekija', 'Čehija', 'Česká republika'),
('Нидерланды', 'Нiдерланди', 'Нідэрлянды', 'Netherlands', 'Holanda', 'Países Baixos', 'Niederlande', 'Pays-Bas', 'Olanda', 'Holandia', 'オランダ', 'Nyderlandai', 'Nīderlande', 'Nizozemsko'),
('Виргинские острова, Британские', 'Вiргiнськi острови, Британськi', 'Віргінскія выспы, Брытанскія', 'British Virgin Islands', 'Islas Vírgenes Británicas', 'Ilhas Virgens Britânicas', 'Britische Jungferninseln', 'Iles Vierges Britanniques', 'Isole Virgin Britanniche', 'Brytyjskie Wyspy Dziewicze', 'イギリス領ヴァージン諸島', 'Mergelių salos, Didžioji Britanija', 'Virdžīnijas salas, Apvienotā Karaliste', 'Britské Panenské ostrovy'),
('Сан-Томе и Принсипи', 'Сан-Томе i Прiнсiпi', 'Сан-Тамэ й Прынсыпі', 'São Tomé and Príncipe', 'Santo Tomé y Príncipe', 'São Tomé e Príncipe', 'São Tomé und Príncipe', 'Sao-Tomé et Principe', 'São Tomé e Príncipe', 'Wyspy São Tomé i Książęca', 'サントメ・プリンシペ', 'San Tomė ir Prinsipė', 'San Tome un Prinsipi', 'Svatý Tomáš a Princův ostrov'),
('Бурунди', 'Бурундi', 'Бурундзі', 'Burundi', 'Burundi', 'Burundi', 'Burundi', 'Burundi', 'Burundi', 'Burundi', 'ブルンジ', 'Burundis', 'Burundi', 'Burundi'),
('Суринам', 'Сурiнам', 'Сурынам', 'Suriname', 'Surinam', 'Suriname', 'Suriname', 'Surinam', 'Suriname', 'Surinam', 'スリナム', 'Surinamas', 'Surinama', 'Surinam'),
('Острова Кука', 'Острови Кука', 'Выспы Кука', 'Cook Islands', 'Islas Cook', 'Ilha Cook', 'Cook-Inseln', 'Iles Cook', 'Isole Cook', 'Wyspy Cooka', 'クック諸島', 'Kuko salos', 'Kūka salas', 'Cookovy ostrovy'),
('Святая Елена', 'Святої Єлени', 'Сьвятая Алена', 'Saint Helena', 'Santa Helena', 'Santa Elena', 'St. Helena', 'Sainte Hélène', 'Sant''Elena', 'Wyspa Św. Heleny', 'セントヘレナ', 'ŠV. Elenos sala', 'Svētās Helēnas Sala', 'Svatá Helena'),
('Сент-Китс и Невис', 'Сент-Китс i Невiс', 'Сэнт-Кітз і Нэвіс', 'Saint Kitts and Nevis', 'San Cristóbal y Nieves', 'São Cristóvão e Nevis', 'St. Kitts und Nevis', 'Saint-Christophe et Niévès', 'Saint Kitts e Nevis', 'Saint Kitts i Nevis', 'クリストファー・ネイビス', 'Sent Kitsas ir Nevis', 'Sentkitsa un Nevisa', 'Svatý Kryštof a Nevis'),
('Фолклендские острова', 'Фолклендськi острови', 'Фальклэндзкія выспы', 'Falkland Islands', 'Islas Malvinas', 'Ilhas Malvinas', 'Falkland Inseln', 'Iles Malouines', 'Isole Falkland/Malvinas', 'Wyspy Falklandzkie', 'フォークランド諸島', 'Folklendų salos', 'Folklendas salas', 'Falklandské ostrovy'),
('Вануату', 'Вануату', 'Вануату', 'Vanuatu', 'Vanuatu', 'Vanuatu', 'Vanuatu', 'Vanuatu', 'Vanuatu', 'Vanuatu', 'バヌアツ', 'Vanuatu', 'Vanuatu', 'Vanuatu'),
('Южная Корея', 'Пiвденна Корея', 'Паўднёвая Карэя', 'South Korea', 'Corea del Sur', 'Coreia do Sul', 'Südkorea', 'Corée du Sud', 'Corea del Sud', 'Korea Południowa', '大韓民国', 'Pietų Korėja', 'Dienvidkoreja', 'Jižní Korea'),
('Южно-Африканская Республика', 'Пiвденно-Африканська Республiка', 'Паўднёва-Афрыканская Рэспубліка', 'South Africa', 'República de Sudáfrica', 'República da África do Sul', 'Südafrika', 'Afrique du Sud', 'Sud Africa', 'RPA', '南アフリカ共和国', 'Pietų Afrikos Respublika', 'Dienvidāfrikas Republika', 'Jihoafrická republika'),
('Вьетнам', 'В''єтнам', 'Віетнам', 'Vietnam', 'Vietnam', 'Vietname', 'Vietnam', 'Vietnam', 'Vietnam', 'Wietnam', 'ヴェトナム', 'Vietnamas', 'Vjetnama', 'Vietnam'),
('Конго, демократическая республика', 'Конго, демократична республiка', 'Конга, дэмакратычная рэспубліка', 'Congo, Democratic Republic', 'República Democrática del Congo', 'República Democrática do Congo', 'Kongo, Demokratische Republik', 'République démocratique du Congo', 'Congo, Repubblica Democratica', 'Demokratyczna Republika Konga', 'コンゴ民主共和国', 'Kongo Demokratinė Respublika', 'Kongo Demokrātiskā Republika', 'Demokratická republika Kongo'),
('Египет', 'Єгипет', 'Эгіпэт', 'Egypt', 'Egipto', 'Egito', 'Ägypten', 'Egypte', 'Egitto', 'Egipt', 'エジプト', 'Egiptas', 'Ēģipte', 'Egypt'),
('Кирибати', 'Кiрiбатi', 'Кірыбаты', 'Kiribati', 'Kiribati', 'Kiribati', 'Kiribati', 'Kiribati', 'Kiribati', 'Kiribati', 'キリバス', 'Kiribatis', 'Ķiribati', 'Kiribati'),
('Пуэрто-Рико', 'Пуерто-Рiко', 'Пуэрта-Рыка', 'Puerto Rico', 'Puerto Rico', 'Porto Rico', 'Puerto Rico', 'Porto Rico', 'Puerto Rico', 'Puerto Rico', 'プエルトリコ', 'Puerto Rikas', 'Puerto Riko', 'Portoriko'),
('Эритрея', 'Ерiтрея', 'Эрытрэя', 'Eritrea', 'Eritrea', 'Eritreia', 'Eritrea', 'Erythrée', 'Eritrea', 'Erytrea', 'エリトリア', 'Eritrėja', 'Eritreja', 'Eritrea'),
('Острова Теркс и Кайкос', 'Острови Теркс i Кайкос', 'Выспы Тэркс і Кайкос', 'Turks and Caicos Islands', 'Islas Turcas y Caicos', 'Ilhas Turcas e Caicos', 'Turks- und Caicos Inseln', 'Iles Turques et Caïques', 'Isole Turks e Caicos', 'Turks i Caicos', 'タークス・カイコス諸島', 'Terkso ir Kaikoso salos', 'Tērksas un Kaikosas', 'Ostrovy Turks a Caicos'),
('Парагвай', 'Парагвай', 'Параґвай', 'Paraguay', 'Paraguay', 'Paraguai', 'Paraguay', 'Paraguay', 'Paraguay', 'Paragwaj', 'パラグアイ', 'Paragvajus', 'Paragvaja', 'Paraguay'),
('Польша', 'Польща', 'Польшча', 'Poland', 'Polonia', 'Polónia', 'Polen', 'Pologne', 'Polonia', 'Polska', 'ポーランド', 'Lenkija', 'Polija', 'Polsko'),
('Сент-Винсент', 'Сент-Вiнсент', 'Сэнт-Вінцэнт', 'Saint Vincent and the Grenadines', 'San Vicente', 'São Vicente', 'St. Vincent und die Grenadinen', 'Saint-Vincent', 'Saint Vincent e Grenadines', 'Saint Vincent i Grenadyny', 'セントビンセント', 'Sent Vincentas', 'Sentvinsenta', 'Svatý Vincent a Grenadiny'),
('Палестинская автономия', 'Палестинська автономiя', 'Палестынская аўтаномія', 'Palestine', 'Palestina', 'Autoridade Nacional Palestiniana', 'Palestina', 'Palestine', 'ANP', 'Palestyna', 'パレスティナ自治区', 'Palestinos teritorija', 'Palestīnas autonomija', 'Palestina'),
('Шпицберген и Ян Майен', 'Шпiцберген i Ян Майен', 'Шпіцбэрґен і Ян Маен', 'Svalbard and Jan Mayen', 'Spitsbergen y Jan Mayen', 'Spitsbergen  e Jan Mayen', 'Svalbard und Jan Mayen', 'Spitzberg et Jan Mayen', 'Svalbard e Jan Mayen', 'Svalbard i Jan Mayen', 'スピッツベルゲン島・ヤンマイエン島', 'Svalbardo ir Jan Majen salos', 'Špicbergena', 'Špicberky a Jan Mayen'),
('Барбадос', 'Барбадос', 'Барбадос', 'Barbados', 'Barbados', 'Barbados', 'Barbados', 'Barbades', 'Barbados', 'Barbados', 'バルバドス', 'Barbadosas', 'Barbadosa', 'Barbados'),
('Буркина-Фасо', 'Буркина-Фасо', 'Буркіна-Фасо', 'Burkina Faso', 'Burkina Faso', 'Burkina Faso', 'Burkina Faso', 'Burkina Faso', 'Burkina Faso', 'Burkina Faso', 'ブルキナファソ', 'Burkina Faso', 'Burkinafaso', 'Burkina Faso'),
('Колумбия', 'Колумбiя', 'Калюмбія', 'Colombia', 'Colombia', 'Colômbia', 'Kolumbien', 'Colombie', 'Colombia', 'Kolumbia', 'コロンビア', 'Kolumbija', 'Kolumbija', 'Kolumbie'),
('Исландия', 'Iсландiя', 'Ісьляндыя', 'Iceland', 'Islandia', 'Islândia', 'Island', 'Islande', 'Islanda', 'Islandia', 'アイスランド', 'Islandija', 'Īslande', 'Island'),
('Мальдивы', 'Мальдiви', 'Мальдывы', 'Maldives', 'Maldivas', 'Maldivas', 'Malediven', 'Maldives', 'Maldive', 'Malediwy', 'モルジブ', 'Maldyvai', 'Maldīvas', 'Maledivy'),
('Маршалловы Острова', 'Маршаловi острови', 'Маршалавыя Выспы', 'Marshall Islands', 'Islas Marshall', 'Ilhas Marshall', 'Marshallinseln', 'Iles Marshall', 'Isole Marshall', 'Wyspy Marshalla', 'マーシャル諸島', 'Maršalų salos', 'Maršalu salas', 'Marhallovy ostrovy'),
('Микронезия, федеративные штаты', 'Мiкронезiя, федеративнi штати', 'Мікранэзія, фэдэратыўныя штаты', 'Micronesia', 'Estados Federados de Micronesia', 'Micronésia', 'Mikronesien', 'Etats fédérés de Micronésie', 'Micronesia', 'Mikronezja', 'ミクロネシア連邦', 'Mikronezijos Federacinės Valstijos', 'Mikronēzija', 'Mikronésie'),
('Питкерн', 'Пiткерн', 'Піткэрн', 'Pitcairn Islands', 'Islas Pitcairn', 'Ilhas Pitcairn', 'Pitcairn-Inseln', 'Iles Pitcairn', 'Isole Pitcairn', 'Wyspy Pitcairn', 'ピトケアン諸島', 'Pitkernas', 'Pitkerna', 'Pitcairnovy ostrovy'),
('Сент-Пьер и Микелон', 'Сент-Пьєр i Мiкелон', 'Сэн-П’ер і Мікелён', 'Saint Pierre and Miquelon', 'San Pedro y Miguelón', 'Saint-Pierre e Miquelon', 'Saint-Pierre und Miquelon', 'Saint-Pierre et Miquelon', 'Saint Pierre e Miquelon', 'Saint Pierre i Miquelon', 'サンピエール島・ミクロン島', 'Sen Pjeras ir Mikelonas', 'Senpjēra un Mikelona', 'Saint-Pierre a Miquelon'),
('Швеция', 'Швецiя', 'Швэцыя', 'Sweden', 'Suecia', 'Suécia', 'Schweden', 'Suède', 'Svezia', 'Szwecja', 'スウェーデン', 'Švedija', 'Zviedrija', 'Švédsko'),
('Американское Самоа', 'Американське Самоа', 'Амэрыканскае Самоа', 'American Samoa', 'Samoa Americana', 'Samoa Americana', 'Amerikanisch Samoa', 'Samoa américaines', 'Samoa Americana', 'Samoa Amerykańskie', 'アメリカ領サモア', 'Amerikos Samoa', 'Amerikas Samoa', 'Americká Samoa'),
('Антигуа и Барбуда', 'Антiгуа i Барбуда', 'Антыгуа і Барбуда', 'Antigua and Barbuda', 'Antigua y Barbuda', 'Antígua e Barbuda', 'Antigua und Barbuda', 'Antigua et Barbuda', 'Antigua e Barbuda', 'Antigua i Barbuda', 'アンティグア・バーブーダ', 'Antikva ir Barbuda', 'Antigva un Barbuda', 'Antigua a Barbuda'),
('Аргентина', 'Аргентина', 'Аргентына', 'Argentina', 'Argentina', 'Argentina', 'Argentinien', 'Argentine', 'Argentina', 'Argentyna', 'アルゼンチン', 'Argentina', 'Argentīna', 'Argentina'),
('Армения', 'Вiрменiя', 'Арменія', 'Armenia', 'Armenia', 'Arménia', 'Armenien', 'Arménie', 'Armenia', 'Armenia', 'アルメニア', 'Armėnija', 'Armēnija', 'Arménie'),
('Камбоджа', 'Камбоджа', 'Камбоджа', 'Cambodia', 'Camboya', 'Camboja', 'Kambodscha', 'Cambodge', 'Cambogia', 'Kambodża', 'カンボジア', 'Kambodža', 'Kambodža', 'Kambodža'),
('Бонайре, Синт-Эстатиус и Саба', 'Бонайре, Сінт-Естатіус і Саба', 'Банайрэ, Сінт-Эстатыюс і Саба', 'Bonaire, Sint Eustatius and Saba', 'Bonaire, San Eustaquio y Saba', 'Bonaire, Santo Eustáquio e Saba ', 'Bonaire, Sint Eustatius und Saba', 'Bonaire, Saint-Eustache et Saba', 'Bonaire, Sint Eustatius e Saba', 'Bonaire, Sint Eustatius i Saba', 'BES諸島', 'Bonairė, Sint Estatijus ir Saba', 'Bonaire, Sint Eustatius and Saba', 'Karibské Nizozemsko'),
('Португалия', 'Португалiя', 'Партугалія', 'Portugal', 'Portugal', 'Portugal', 'Portugal', 'Portugal', 'Portogallo', 'Portugalia', 'ポルトガル', 'Portugalija', 'Portugāle', 'Portugalsko'),
('Сент-Люсия', 'Сент-Люсiя', 'Сэнт-Люсія', 'Saint Lucia', 'Santa Lucía', 'Santa Lúcia', 'St. Lucia', 'Sainte-Lucie', 'Saint Lucia', 'Santa Lucia', 'セントルシア', 'Sent Liucija', 'Sentlusija', 'Svatá Lucie'),
('Босния и Герцеговина', 'Боснiя i Герцеговина', 'Босьнія й Герцаґавіна', 'Bosnia and Herzegovina', 'Bosnia y Herzegovina', 'Bósnia e Herzegovina', 'Bosnien-Herzegowina', 'Bosnie Herzégovine', 'Bosnia Herzegovina', 'Bośnia and Herzegowina', 'ボスニア・ヘルツェゴビナ', 'Bosnija ir Hercegovina', 'Bosnija un Hercogovīna', 'Bosna a Hercegovina'),
('Лихтенштейн', 'Лiхтенштейн', 'Ліхтэнштайн', 'Liechtenstein', 'Liechtenstein', 'Liechtenstein', 'Liechtenstein', 'Liechtenstein', 'Liechtenstein', 'Liechtenstein', 'リヒテンシュタイン', 'Lichtenšteinas', 'Lihtenšteina', 'Lichtenštejnsko'),
('Французская Полинезия', 'Французька Полiнезiя', 'Француская Палінэзія', 'French Polynesia', 'Polinesia Francesa', 'Polinésia Francesa', 'Französisch Polynesien', 'Polynésie française', 'Polinesia Francese', 'Polinezja Francuska', 'フランス領ポリネシア', 'Prancūzijos Polinezija', 'Fraņču Polinēzija', 'Francouzská Polynésie');
